Error in file(file, "rt") : cannot open the connection
Calls: MergeToyFile -> MergeUntil -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted
[1] "20000" " : "   "0"    
